#!/bin/bash

mode=$(makoctl mode)

if [[ "$mode" == *"do-not-disturb"* ]]; then
    icon="󰂛"   # muted bell
    class="enabled"
else
    icon="󰂚"   # normal bell
    class="disabled"
fi

printf '{"text":"%s %s","class":"%s"}\n' "$icon" "$text" "$class"
