#!/bin/bash

# cek player aktif
player=$(playerctl -l 2>/dev/null | head -n1)

# kalau tidak ada
if [ -z "$player" ]; then
    printf '{"text":"󰝛 No Media","class":"muted"}\n'
    exit
fi

# ambil status
status=$(playerctl status 2>/dev/null)

# ambil metadata
artist=$(playerctl metadata artist 2>/dev/null)
title=$(playerctl metadata title 2>/dev/null)

# potong biar tidak kepanjangan
max_len=25
text="$artist - $title"
text=${text:0:$max_len}

# ICON
if [ "$status" = "Playing" ]; then
    icon="󰏤"
else
    icon="󰐊"
fi

# OUTPUT
printf '{"text":"%s %s","class":"normal","tooltip":"%s - %s"}\n' \
"$icon" "$text" "$artist" "$title"
