#!/bin/bash

choice=$(printf "󰒲 Sleep\n Lock\n󰍃 Logout\n󰜉 Reboot\n Shutdown" | rofi -dmenu -i -p "Power")

case "$choice" in
    "󰒲 Sleep")
        hyprlock & sleep 0.5 && loginctl suspend
        ;;
    " Lock")
        hyprlock
        ;;
    "󰍃 Logout")
        hyprctl dispatch exit
        ;;
    "󰜉 Reboot")
        loginctl reboot
        ;;
    " Shutdown")
        loginctl poweroff
        ;;
esac
