#!/usr/bin/env bash

DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
WALL_DIR="$DATA_HOME/wallpapers"
CURRENT="$WALL_DIR/.current.wall"

mkdir -p "$WALL_DIR" || exit 1

set_link() {
ln -sfn "$(realpath "$1")" "$CURRENT"
}

set_wall() {
local img="$1"

pkill swaybg 2>/dev/null
sleep 0.1

swaybg -i "$img" -m fill & disown

set_link "$img"
}

get_random() {
find "$WALL_DIR" -type f | grep -Ei '\.(jpg|png|jpeg)$' | shuf -n 1
}

apply_current() {
if [[ -L "$CURRENT" ]]; then
wall=$(readlink -f "$CURRENT")
[[ -f "$wall" ]] && set_wall "$wall" && return
fi

set_wall "$(get_random)"
}

case "$1" in
--random)
set_wall "$(get_random)"
;;
--current)
apply_current
;;
*)
[[ -f "$1" ]] && set_wall "$1"
;;
esac
