# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
# -------------------------------------------------------------------


# Session
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Environment (Wayland, GPU, app flags)
source = ~/.config/hypr/conf/env.conf

# Displays
source = ~/.config/hypr/conf/monitors.conf

# Input & core behavior
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/misc.conf

# Program variables (terminal, browser, launcher, dll.)
source = ~/.config/hypr/conf/programs.conf

# Autostart (daemons, tray, services)
source = ~/.config/hypr/conf/autostart.conf

# Visuals
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/animation.conf

# Layout & workspaces
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/workspaces.conf

# Keybindings
source = ~/.config/hypr/conf/keybinds.conf

# Window rules
source = ~/.config/hypr/conf/rules.conf
