#  █████╗ ██████╗ ██████╗ ███████╗ █████╗ ██████╗  █████╗ ███╗   ██╗ ██████╗███████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗  ██║██╔════╝██╔════╝     
# ███████║██████╔╝██████╔╝█████╗  ███████║██████╔╝███████║██╔██╗ ██║██║     █████╗     
# ██╔══██║██╔═══╝ ██╔═══╝ ██╔══╝  ██╔══██║██╔══██╗██╔══██║██║╚██╗██║██║     ██╔══╝   
# ██║  ██║██║     ██║     ███████╗██║  ██║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗   
# ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝  
#-----------------------------------------------------------------------------------

# ==========================
# WINDOW DECORATION
# ==========================
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2

    col.active_border = rgb(b4befe) rgb(f5c2e7) 45deg
    col.inactive_border = rgba(00000000)

    resize_on_border = true
    layout = dwindle
    general {
    # allow_tearing = false
    }
}


# ==========================
# DECORATION
# ==========================
decoration {
    rounding = 10
    dim_special = 0.3

    #drop_shadow = no
    
    
    blur {
        enabled = yes
        size = 3
        passes = 1
        new_optimizations = on
        ignore_opacity = off
        xray = false
    }
}
