# ██████╗ ██████╗  ██████╗  ██████╗ ██████╗  █████╗ ███╗   ███╗███████╗
# ██╔══██╗██╔══██╗██╔═══██╗██╔════╝ ██╔══██╗██╔══██╗████╗ ████║██╔════╝
# ██████╔╝██████╔╝██║   ██║██║  ███╗██████╔╝███████║██╔████╔██║███████╗
# ██╔═══╝ ██╔══██╗██║   ██║██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║╚════██║
# ██║     ██║  ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║███████║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
#----------------------------------------------------------------------

# ==========================
# CORE
# ==========================
$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun -show-icons 


# ==========================
# BROWSER
# ==========================
$browser = firefox


# ==========================
# EDITOR / DEV
# ==========================
$editor = code


# ==========================
# SYSTEM
# ==========================
$lock = hyprlock
$logout = hyprctl dispatch exit
$shutdown = loginctl poweroff
$reboot = loginctl reboot
$suspend = loginctl suspend && hyprlock


# ==========================
# FILE / SYSTEM TOOLS
# ==========================
$explorer = nemo


# ==========================
# MEDIA
# ==========================
$music = spotify
$video = mpv
$image = imv


# ==========================
# NETWORK / BLUETOOTH
# ==========================
$wifi = nm-connection-editor
$bluetooth = blueman-manager


# ==========================
# UTILITY
# ==========================
$calculator = qalculate-qt
$notes = obsidian
$monitor = btop
$process = kitty -e btop


# ==========================
# SCREENSHOT / RECORDING
# ==========================
$screenshot = flameshot gui
$record = wf-recorder


# ==========================
# CLIPBOARD
# ==========================
$clipboard = cliphist list | fuzzel -dmenu | cliphist decode | wl-copy


# ==========================
# POWER MENU (OPTIONAL)
# ==========================
$powermenu = wlogout



