#!/usr/bin/env bash

WALL_DIR="$HOME/.local/share/wallpapers"

IMG=$(
    find "$WALL_DIR" \
        -maxdepth 1 \
        -type f \
        ! -name "current" |
    shuf -n 1
)

~/.config/AikoAi/wallpaper-set "$IMG"
